
spring:
  application:
    name: maersk-backend
  datasource:
    url: jdbc:mysql://localhost:3306/couponservice?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true